# Generated by Django 3.2 on 2022-10-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dress',
            old_name='heading',
            new_name='title',
        ),
    ]
