# Generated by Django 3.2 on 2022-10-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApi', '0002_rename_heading_dress_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_no',
            new_name='product_tag',
        ),
    ]
